name = "holomime-site"
main = "./dist/_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "holomime.dev", custom_domain = true },
  { pattern = "www.holomime.dev", custom_domain = true },
  { pattern = "app.holomime.dev", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"
